var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":44,"id":2388,"methods":[{"el":12,"sc":2,"sl":9},{"el":17,"sc":2,"sl":14},{"el":22,"sc":2,"sl":19},{"el":27,"sc":2,"sl":24},{"el":32,"sc":2,"sl":29},{"el":37,"sc":2,"sl":34},{"el":42,"sc":2,"sl":39}],"name":"PurchaseYearlyPassRequestTest","sl":7}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_1":{"methods":[{"sl":29}],"name":"testSetMobileDeviceMAC","pass":false,"statements":[{"sl":31}]},"test_10":{"methods":[{"sl":9}],"name":"testPurchaseYearlyPassRequest","pass":false,"statements":[{"sl":11}]},"test_1159":{"methods":[{"sl":39}],"name":"testSetDate","pass":false,"statements":[{"sl":41}]},"test_1355":{"methods":[{"sl":14}],"name":"testGetMobileDeviceMAC","pass":false,"statements":[{"sl":16}]},"test_1490":{"methods":[{"sl":19}],"name":"testGetVersion","pass":false,"statements":[{"sl":21}]},"test_1550":{"methods":[{"sl":9}],"name":"testPurchaseYearlyPassRequest","pass":false,"statements":[{"sl":11}]},"test_1573":{"methods":[{"sl":29}],"name":"testSetMobileDeviceMAC","pass":false,"statements":[{"sl":31}]},"test_40":{"methods":[{"sl":14}],"name":"testGetMobileDeviceMAC","pass":false,"statements":[{"sl":16}]},"test_419":{"methods":[{"sl":34}],"name":"testSetVersion","pass":false,"statements":[{"sl":36}]},"test_421":{"methods":[{"sl":24}],"name":"testGetDate","pass":false,"statements":[{"sl":26}]},"test_499":{"methods":[{"sl":24}],"name":"testGetDate","pass":false,"statements":[{"sl":26}]},"test_52":{"methods":[{"sl":19}],"name":"testGetVersion","pass":false,"statements":[{"sl":21}]},"test_539":{"methods":[{"sl":34}],"name":"testSetVersion","pass":false,"statements":[{"sl":36}]},"test_787":{"methods":[{"sl":39}],"name":"testSetDate","pass":false,"statements":[{"sl":41}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [10, 1550], [], [10, 1550], [], [], [1355, 40], [], [1355, 40], [], [], [1490, 52], [], [1490, 52], [], [], [421, 499], [], [421, 499], [], [], [1, 1573], [], [1, 1573], [], [], [419, 539], [], [419, 539], [], [], [1159, 787], [], [1159, 787], [], [], []]
