var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":64,"id":1508,"methods":[{"el":12,"sc":2,"sl":9},{"el":17,"sc":2,"sl":14},{"el":22,"sc":2,"sl":19},{"el":27,"sc":2,"sl":24},{"el":32,"sc":2,"sl":29},{"el":37,"sc":2,"sl":34},{"el":42,"sc":2,"sl":39},{"el":47,"sc":2,"sl":44},{"el":52,"sc":2,"sl":49},{"el":57,"sc":2,"sl":54},{"el":62,"sc":2,"sl":59}],"name":"UpdateUserCommandTest","sl":7}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_132":{"methods":[{"sl":54}],"name":"testGetException","pass":false,"statements":[{"sl":56}]},"test_133":{"methods":[{"sl":39}],"name":"testSetPassword","pass":false,"statements":[{"sl":41}]},"test_139":{"methods":[{"sl":29}],"name":"testSetLastName","pass":false,"statements":[{"sl":31}]},"test_157":{"methods":[{"sl":14}],"name":"testSetId","pass":false,"statements":[{"sl":16}]},"test_161":{"methods":[{"sl":9}],"name":"testExecute","pass":false,"statements":[{"sl":11}]},"test_28":{"methods":[{"sl":44}],"name":"testSetSalt","pass":false,"statements":[{"sl":46}]},"test_35":{"methods":[{"sl":49}],"name":"testSetVersion","pass":false,"statements":[{"sl":51}]},"test_49":{"methods":[{"sl":59}],"name":"testIsSucceed","pass":false,"statements":[{"sl":61}]},"test_69":{"methods":[{"sl":19}],"name":"testSetRoles","pass":false,"statements":[{"sl":21}]},"test_7":{"methods":[{"sl":34}],"name":"testSetUsername","pass":false,"statements":[{"sl":36}]},"test_79":{"methods":[{"sl":24}],"name":"testSetFirstName","pass":false,"statements":[{"sl":26}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [161], [], [161], [], [], [157], [], [157], [], [], [69], [], [69], [], [], [79], [], [79], [], [], [139], [], [139], [], [], [7], [], [7], [], [], [133], [], [133], [], [], [28], [], [28], [], [], [35], [], [35], [], [], [132], [], [132], [], [], [49], [], [49], [], [], []]
